# Generated by Django 5.2 on 2025-06-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('style_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('og_min', models.FloatField(help_text='Original Gravity minimum')),
                ('og_max', models.FloatField(help_text='Original Gravity maximum')),
                ('fg_min', models.FloatField(help_text='Final Gravity minimum')),
                ('fg_max', models.FloatField(help_text='Final Gravity maximum')),
                ('ibu_min', models.IntegerField(help_text='IBU minimum')),
                ('ibu_max', models.IntegerField(help_text='IBU maximum')),
                ('srm_min', models.IntegerField(help_text='SRM color minimum')),
                ('srm_max', models.IntegerField(help_text='SRM color maximum')),
                ('abv_min', models.FloatField(help_text='ABV minimum')),
                ('abv_max', models.FloatField(help_text='ABV maximum')),
            ],
            options={
                'ordering': ['style_code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_batch_size', models.FloatField(default=20.0, help_text='Preferred batch size in liters')),
                ('brewing_efficiency', models.FloatField(default=75.0, help_text='Average brewing efficiency %')),
                ('equipment_notes', models.TextField(blank=True, help_text='Notes about your brewing equipment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
