# Generated by Django 5.2 on 2025-06-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_brews', models.IntegerField(default=0)),
                ('total_batches_liters', models.FloatField(default=0.0)),
                ('successful_brews', models.IntegerField(default=0)),
                ('failed_brews', models.IntegerField(default=0)),
                ('avg_efficiency', models.FloatField(blank=True, null=True)),
                ('best_efficiency', models.FloatField(blank=True, null=True)),
                ('worst_efficiency', models.FloatField(blank=True, null=True)),
                ('avg_og', models.FloatField(blank=True, null=True)),
                ('avg_fg', models.FloatField(blank=True, null=True)),
                ('avg_abv', models.FloatField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_cost_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_brew_time_hours', models.FloatField(blank=True, null=True)),
                ('avg_fermentation_days', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
